### ISSUE TITLE
Bug with Modpack 

### ISSUE THREAD

**Issue by francerobin** [finallion/VillagersPlus#10]
[crash-2023-08-09_14.39.22-client.txt](https://github.com/finallion/VillagersPlus_-FABRIC-/files/12305993/crash-2023-08-09_14.39.22-client.txt)

**Comment by finallion** [comment]
Thank you! Can you use this version, repeat the process for when the crash happened and send me the log again? It narrows the error down, so I know where to start looking!

[VillagersPlus Crash-Test 2.1.zip](https://github.com/finallion/VillagersPlus_-FABRIC-/files/12312524/VillagersPlus.Crash-Test.2.1.zip)

**Comment by francerobin** [comment]
That fixed the issue, no longer crashes!

**Comment by finallion** [comment]
I'm afraid it only masks the error. Could you post the logs nethertheless?

**Comment by francerobin** [comment]
[latest.log](https://github.com/finallion/VillagersPlus_-FABRIC-/files/12317112/latest.log)

here you are!
