### ISSUE TITLE
Game Crashes when Villages load in

### ISSUE THREAD

**Issue by Aaron-949** [finallion/VillagersPlus#12]
[crash-2023-08-19_09.15.39-client.txt](https://github.com/finallion/VillagersPlus-FABRIC/files/12386313/crash-2023-08-19_09.15.39-client.txt)

This issue does not recreate when using the mod alone. but in my mod packs it recreates every time. is there a mod interfering with it and if so how do i fix it? preferably without removing mods but if i have to, i guess i can make some sacrifices.

**Comment by finallion** [comment]
Please update your version to 1.9.1 and check if the issue persists. If so, reopen this one again with the new logs.

**Comment by Aaron-949** [comment]
i am unable to find the version 1.9.1 file the next release after 1.9 is 1.10. where can i get this file?

**Comment by finallion** [comment]
My bad, it was still hidden.
Here is the link one it is approved (1.9.2)
https://legacy.curseforge.com/minecraft/mc-mods/villagersplus-fabric/files/4713374
