### ISSUE TITLE
Oak Flower Tub isn't a valid job site

### ISSUE THREAD

**Issue by drakray** [finallion/VillagersPlus#14]
using:
Minecraft 1.20.1
NeoForge 47.1.76
VillagerPlus 3.0
BunchaOtherMods™

Other FlowerTub seem valid

**Comment by drakray** [comment]
Villager seem to take a job from Oak, but stay Unemployed

**Comment by ImpulsiveLass** [comment]
Can verify, only oak has the issue (you can tell they try based on the being hired particle but they remain unemployed) 
All other tubs work as intended

**Comment by finallion** [comment]
Fixed in 3.1
