### ISSUE TITLE
Can't use Flower Tubs

### ISSUE THREAD

**Issue by FISHPUPS** [finallion/VillagersPlus#15]
Able to craft flower tubs & place them, but cannot place any plants in any of the tubs. Currently using All of Fabric 6 modpack v1.10.0 (Minecraft 1.19.2, Fabric 0.14.22).

Unsure if this is an issue within the entire modpack or with this mod specifically, but figured I'd start here. Thank you!

**Comment by finallion** [comment]
Did you try the mod alone and if so, does it work there? I'm assuming it's a compatability issue.
