### ISSUE TITLE
Flower Tub eats two copies of a tall flower when inserting.

### ISSUE THREAD

**Issue by Angular-Angel** [finallion/VillagersPlus#17]
To reproduce: right click on an empty flower tub with a stack of more than one rose bush. The stack will be decremented by two, instead of one. You can still use a single rose bush, and it places it in the tub, eating the entire stack.

**Comment by Angular-Angel** [comment]
This also happens with saplings.

**Comment by finallion** [comment]
Fixed in 3.1
