### ISSUE TITLE
Breaks mods that add Windowed Fullscreen (Borderless)

### ISSUE THREAD

**Issue by XSentinelu** [finallion/VillagersPlus#20]
I'm using [this](https://www.curseforge.com/minecraft/mc-mods/windowed-fullscreen) mod which replace fullscreen mode with windowed fullscreen, currently it is the only workaround to play Minecraft with HDR monitor. And loading VillagersPlus mod somehow breakes it, forcing exclusive fullscreen. 

Minecraft version: 1.20.1 Fabric
Mod version: 2.1 for Fabric

**Comment by finallion** [comment]
And don't see any relation between the two mods, nor does VP affect anything outside normal gameplay. And as there is neither a source code or an issue page I suggest contacting the developer of the fullscreen mod.
