### ISSUE TITLE
Oak Flower Tub not working

### ISSUE THREAD

**Issue by bons66** [finallion/VillagersPlus#21]
MC 1.21.1
Fabric Loader 0.14.24
Mods
architectury-9.1.12-fabric.jar
cloth-config-11.1.106-fabric.jar
fabric-api-0.90.7+1.20.1.jar
RoughlyEnoughItems-12.0.674.jar
VillagersPlus_3.0_(FABRIC)_for_1.20.1.jar

Villager doesn't get a profession with Oak Flower Tub. Doesn't matter - naturally generated or crafted Oak Flower Tub.
All other types Flower Tub - work fine.

[latest.log](https://github.com/finallion/VillagersPlus/files/13422872/latest.log)

**Comment by jpcrowe** [comment]
Can confirm for Forge
MC 1.21.1
Forge 47.1.3
architectury-9.1.12-forge.jar
cloth-config-11.1.106-forge.jar
VillagersPlus_3.0_(FORGE)_for_1.20.1.jar

**Comment by finallion** [comment]
Fixed in 3.1
