### ISSUE TITLE
Villagerplus not showing skins

### ISSUE THREAD

**Issue by ArrafiDinner** [finallion/VillagersPlus#27]
the Villagerplus not showing skin idk why.
Version: 1.20.1 Fabric Modrinth
Aternos Server

<img width="520" alt="image" src="https://github.com/finallion/VillagersPlus/assets/133111249/e873d354-fdd4-4ed1-a958-7c6d835ac0d2">

<img width="459" alt="image" src="https://github.com/finallion/VillagersPlus/assets/133111249/8f94cfd3-036c-4631-9433-15e8c9e8485c">

**Comment by finallion** [comment]
Does the issue occur with the mod alone?

**Comment by ArrafiDinner** [comment]
My Apologies dear owner, 
the issue is **SOLVED** by deleting one of my unused spesific mod in local folder.
the galosphere effect the skin texture.
 
it's all because i have the  galosphere mod in local folder but also that galeosphere mod is not avaiable (deleted) my Aternos Server...
