### ISSUE TITLE
Aquarium for villagers

### ISSUE THREAD

**Issue by Nightw4re** [finallion/VillagersPlus#28]
Hi, this is a feature request and not an issue.

I like the idea when you put a villager into a block as it is in easyVillager(Forge).

Basically, you have **an aquarium** and it could work in the same way, you can insert a villager and his working station.

The block might just accept a villager entity and it might be handled by another mod or here but not important, I found few mods allowing create an item from an entity and put it back into a world on another position, eg. "Villager In A Bucket" or "Pickable Villagers".

You can:
* Reduce performance for a server since no AI, pathfinding, etc. is needed anymore
* Villagers will need less space, just one block
* A player is saved in his house against Raid since it is a block and not an entity

**Comment by JustDoom** [comment]
Villager In A Bucket is indeed a mod that does this

**Comment by Nightw4re** [comment]
> Villager In A Bucket is indeed a mod that does this

my point is to have a block for trades instead of entities, not sure if you got my main idea of this

**Comment by JustDoom** [comment]
Sorry, Let me fix it

> I found a few mods allowing create an item from an entity and put it back into a world on another position, eg. "Villager In A Bucket"

Villager In A Bucket is indeed a mod that does this

**Comment by finallion** [comment]
Sorry, I dont feel that this idea goes in the direction I want the mod to go - thank you though for your request, this is just my personal opinion on that
