### ISSUE TITLE
VILLAGERS PLUS vs MORE VILLAGERS

### ISSUE THREAD

**Issue by vinnyg0621** [finallion/VillagersPlus#36]
is this mod better than more villagers? :P
...or which one should I use?

_edit:_
...or should I switch to this mod from that mod?

**Comment by RyanSalad** [comment]
I like this mod a lot more than More Villagers because the workstations actually have uses in this mod. Btw, this isn't really the place to ask these kind of questions

**Comment by vinnyg0621** [comment]
maybe I should switch.
