### ISSUE TITLE
World crashes when I join (Oceanographer's table)

### ISSUE THREAD

**Issue by skim92606** [finallion/VillagersPlus#5]
Yo so I use the Better MC Fabric modpack (v17 HF, 1.19.2) and I asked the dev why I couldn't join, they said to report it here.
It worked fine on previous Better MC versions, but after the modpack updated I kept crashing whenever I joined

[crash-2023-04-07_23.11.51-client.txt](https://github.com/finallion/VillagersPlus_-FABRIC-/files/11192708/crash-2023-04-07_23.11.51-client.txt)

**Comment by finallion** [comment]
Fixed in 3.1
