### ISSUE TITLE
fr_fr

### ISSUE THREAD

**Issue by gkr0013** [finallion/VillagersPlus#7]
Dear,

the fr_fr file for the French version of your mod:

> {
> "container.alchemist_table": "Table d'alchimiste",
> 
> "block.villagersplus.alchemist_table": "Table d'alchimiste",
> "block.villagersplus.occultist_table": "Bassin enchanté",
> "block.villagersplus.oceanographer_table": "Aquarium",
> "block.villagersplus.oak_horticulturist_table": "Bac à fleurs en chêne",
> "block.villagersplus.dark_oak_horticulturist_table": "Bac à fleurs en chêne noir",
> "block.villagersplus.spruce_horticulturist_table": "Bac à fleurs en sapin",
> "block.villagersplus.jungle_horticulturist_table": "Bac à fleurs en acajou",
> "block.villagersplus.birch_horticulturist_table": "Bac à fleurs en bouleau",
> "block.villagersplus.acacia_horticulturist_table": "Bac à fleurs en acacia",
> "block.villagersplus.mangrove_horticulturist_table": "Bac à fleurs en palétuvier",
> "block.villagersplus.crimson_horticulturist_table": "Bac à fleurs carmin",
> "block.villagersplus.warped_horticulturist_table": "Bac à fleurs biscornue",
> 
> "entity.minecraft.villager.alchemist": "Alchimiste",
> "entity.minecraft.villager.occultist": "Occultiste",
> "entity.minecraft.villager.oceanographer": "Océanographe",
> "entity.minecraft.villager.horticulturist": "Jardinier",
> 
> "itemGroup.villagersplus.group": "VillagersPlus"
> }

Thanks ;-)

**Comment by finallion** [comment]
Thanks a lot mate :). Added to the update!
