### ISSUE TITLE
Version 2.0 has bugs

### ISSUE THREAD

**Issue by ghost** [finallion/VillagersPlus#8]
When the world is generated, it will collapse！！

**Comment by finallion** [comment]
Could you provide a bit more info like logs?

**Comment by moninformateur** [comment]
> Could you provide a bit more info like logs?

I suspect I may share the crash with OP. [Here's my crash log on mclo.gs](https://mclo.gs/QZJANk4).

**Comment by finallion** [comment]
Thank you! Can you use this version, repeat the process for when the crash happened and send me the log again?

[VillagersPlus Crash-Test 2.1.zip](https://github.com/finallion/VillagersPlus_-FABRIC-/files/12312497/VillagersPlus.Crash-Test.2.1.zip)

**Comment by moninformateur** [comment]
No crashes anymore!
