### ISSUE TITLE
Grindstone Duplication Glitch

### ISSUE THREAD

**Issue by chorbintime** [finallion/VillagersPlus#9]
Reproducible in BMC2 Fabric v7.5 and unreleased v8

More info @ https://github.com/LunaPixelStudios/Better-MC/issues/1340
Only happens when VillagersPlus is enabled

**Comment by finallion** [comment]
Hm. I can't reproduce the error with the mod and tbh there is nothing in the mod that even remotely touches item handling, enchantments or grindstones. So I'm a bit at loss here...

To be clear: it happens when VP is enabled and it fixes it wenn only VP is removed?

**Comment by chorbintime** [comment]
Yeah it's not VillagersPlus, sorry about that. I could've sworn it was the only mod I disabled when the issue stopped happening. Thank you for the response
